server:
  address: localhost
  port: 5000

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/translator
    username: andrew
    password: tobilko
  security:
    realm-name: application-realm
    encoding-strength: 256